### ISSUE TITLE
Speed-Dial redux To-Do

### ISSUE THREAD

**Issue by DoctorGurke** [Eagle-One-Development/sbox-speed-dial#28]
This is mostly for myself or anybody who decides to chip in on the current effort to put speed-dial onto the new gamemode framework. This is for mechanics that to tick off which ones are already done and which ones arent.

### Core mechanics
- [x] weapon throwing
- [x] throwing damage
- [x] melee punch
- [x] score + combo system
- [x] characters (random)
- [x] drugs
- [x] weapon/drug spawns
- [x] basic round system
- [x] domination
- [x] cause of death + quips (needs to be reevaluated)
- [x] soundtrack
- [x] round system

### Core UI
- [x] ammo
- [x] score + combo
- [x] world hints
- [x] screen events
- [x] scoreboard
- [x] crosshair
- [x] character select
- [x] kill feed
- [x] world hint score popups
- [x] round timer
- [x] top players (as seen in concept)
- [x] "killed by" part in screen event
- [x] active drug icon or indicator
- [x] winner screen at post round
- [ ] map and gamemode voting screen

### Extras
- [x] extra weapons
- [ ] map and gamemode voting
- [ ] post processing
- [ ] #32
- [ ] custom chat
- [ ] ~~settings (needs to be reevaluated)~~

I am going to update this list continuously
